name: Clox CI Workflow

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSYS2 and Install CMake
      run: |
        echo "Setting up MSYS2 and installing CMake"
        pacman -S --noconfirm base-devel mingw-w64-x86_64-cmake
        cmake --version  # Verify CMake is installed

    - name: Verify directory structure
      run: |
        echo "Listing project directory:"
        dir # This will list the contents to ensure we're in the correct place

    - name: Build with CMake
      run: |
        echo "Creating build directory"
        mkdir build
        cd build
        cmake ..
        cmake --build . --verbose  # Added verbose flag for more detailed output

    - name: Run tests (if you have a test suite)
      run: |
        echo "Running tests"
        cd build
        ./tests  # Or replace with your actual test command
